### ISSUE TITLE
The DisplayPDF Droid Example can fail to display PDF

### ISSUE THREAD

**Issue by julesx** [xamarin/recipes#10]
If you do not see the PDF, check your debug output log for the following:

`I/chromium(31570): [INFO:CONSOLE(0)] "XMLHttpRequest cannot load file:///android_asset/Content/pdf-test.pdf. Cross origin requests are only supported for protocol schemes: http, data, chrome, https.", source: file:///android_asset/pdfjs/web/viewer.html?file=file:///android_asset/Content/pdf-test.pdf (0)`

To resolve, add 

`Control.Settings.AllowUniversalAccessFromFileURLs = true;`

to your android web view renderer.

**Comment by davidbritch** [comment]
What circumstances did this occur in? A certain API?

**Comment by julesx** [comment]
To be honest I'm not sure.  With the same API level, I pulled down the fixed droid project, it worked, I implemented it into my project, it failed to display, I made a new project, it worked, so clearly it is something specific to my project but I can't figure out what option it is.

**Comment by davidbritch** [comment]
Added note to doc.
