### ISSUE TITLE
[ios] Load non-web documents recipe solution references missing files

### ISSUE THREAD

**Issue by davidbritch** [xamarin/recipes#12]
This recipe:

https://github.com/xamarin/recipes/tree/master/ios/content_controls/web_view/load_non-web_documents

references three files (.pdf, .docx, .xslx) that are missing from the solution.

**Comment by davidbritch** [comment]
Also need to set window.RootViewController.

**Comment by asb3993** [comment]
Fixed in 5546e5f22a167f0889baf6ef612b349b93a1e638
