### ISSUE TITLE
OnStart is deprecated

### ISSUE THREAD

**Issue by Thaina** [xamarin/recipes#13]

**Comment by conceptdev** [comment]
Please provide more information: what document are you referring to (on what platform)?

**Comment by EcherHet** [comment]
Android Service class, when I override onstart it said it deprecated and it seem like we should use OnStartCommand

And xamarin document still have only onstart sample

**Comment by Thaina** [comment]
Android Service class, when I override onstart it said it deprecated and it seem like we should use OnStartCommand

And xamarin document still have only onstart sample

**Comment by topgenorth** [comment]
I believe it's this sample - https://github.com/xamarin/recipes/tree/master/android/fundamentals/service/create_a_simple_service.
