### ISSUE TITLE
Reverse Geocode Location 

### ISSUE THREAD

**Issue by Goldstrike** [xamarin/recipes#18]
Hello,
I tried to test the sample "**ReverseGeocode**" but I can't get any address and I always get the message "_Could not find any addresses._"...

I have activated the different services that seem necessary:
**INTERNET
ACCESS_FINE_LOCATION
ACCESS_COARSE_LOCATION
ACCESS_LOCATION_EXTRA_COMMANDS
ACCESS_MOCK_LOCATION
ACCESS_NETWORK_STATE
ACCESS_WIFI_STATE**

Would there anything I have forgotten?

**Comment by davidbritch** [comment]
Do you have a Google Maps key?

https://developer.xamarin.com/guides/xamarin-forms/working-with/maps/#Android

**Comment by Goldstrike** [comment]
I had not a Google Map key but  I have created one, and placed it into the **AndroidManifest.xml**:
`  <application android:label="MyApp">
    
    <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="AIzaSyDQyEmYKq7JQjVRHzZxxxxxxxxxxxxxxx" />
  </application>`

But I always have the same result!

I have also remarked that my Play Store doesn't work correctly. I have followed the steps described here:
http://codesmells.net/2015/07/27/installing-the-google-play-store-in-the-microsoft-visual-studio-android-emulator/

The installation works well, but when I launch the Play Store, it closed itself directly...

_**=> Could this explain my problem?**_

**Comment by davidbritch** [comment]
That'll be the problem. You need to ensure that the version of Google Play Services you install matches the Android version of the device profile that you want to use in the emulator. You can find more info at:

https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/debug-on-emulator/visual-studio-android-emulator/

**Comment by Goldstrike** [comment]
I have finally removed and reinstalled the devices from **Visual Studio Emulator for Android**. Then I I reinstall the **GAPPS**, and now the **Play Store** works fine.

But I always meet the same problem: the result of adresses is always null...

Here is a screenshot of this return:
[http://img15.hostingpics.net/pics/559471ReverseGeocode.png](url)

**_=> What could be the problem, if the services, the API key and the emulator seem to be ok?_**

**Comment by davidbritch** [comment]
After testing the sample on the Visual Studio Emulator for Android I can confirm the behavior you're seeing (it not working). I can also confirm that it's not an API key related issue, as you don't actually need an API key to use the Geocoder class.

The sample works correctly in the Xamarin Android Player, and on an actual device. Therefore it looks like an issue with Visual Studio Emulator for Android.

**Comment by Goldstrike** [comment]
Thanks for your return.
I will try with XAP on a Mac, but do you see another way to do this on Visual Studio? Is there an additionnal component allowing to do this?

**Comment by davidbritch** [comment]
I don't see any way around the problem. On Android, the Xamarin.Forms.Maps.Geocoder class uses the Android.Locations.Geocoder class. The Android.Locations.Geocoder.IsPresent property must be true for geocoding/reverse geocoding to work. If you examine the Android.Locations.Geocoder.IsPresent property in an Android project, you'll find the following results returned:

Device - true
XAP on a Mac - true
VSE for Android (ensuring that Location services are enabled in Windows) - false

**Comment by Goldstrike** [comment]
Thanks again David.
I have another question:
- in my first post, I tested the "**ReverseGeocode**" for **Android **(in "recipes-master\android\os_device_resources\geocoder\reverse_geocode_a_location"):
=> the ReverseGeocoder is based on:
`var geo = new Geocoder (this);
var addresses = await geo.GetFromLocationAsync (42.37419, -71.120639, 1);`

- I also tried the "**ReverseGeocode**" project for **Xamarin.Forms** (in "recipes-master\cross-platform\xamarin-forms\Maps\ReverseGeocode"):
=> the ReverseGeocode is based on the Xamarin.Forms.Maps Geocoder:
`var position = new Position (latitude.Value, longitude.Value);
var possibleAddresses = await geoCoder.GetAddressesForPositionAsync (position);`

**_- I want to know what are the advantages brought by the use of the Geocoder Xamarin.Forms.Maps compared to the other solution? Is it only that an API is not needed?_**

For my project, I need to:
1. define the user's position
2. convert the position into address
3. shows somes points of interest on a map
4. calculate the distance between the user and the points of interest

I'm able to define the user's position with the plugin Geolocator. 

**_=> But for the other points, is it really interesting to use Xamarin.Forms.Maps?_**

**Comment by Goldstrike** [comment]
Hi davidbrich, I meet a new problem on iOS this time...

1. When I deploy the project on my iPhone, Visual Studio freezes the half the time, without any reason (no exception or error): I need to kill the Visual Studio process
2. When the deployment works well, or if I relaunch the app directly from my device, I get an exception on `latitude = Convert.ToDouble(coordinates.FirstOrDefault());` : "**Input string was not in a correct format**"
 This exception only occurs when my iPhone is setted in french. When I switch it in english, I don't get this exception...  

**_=> Would you have any idea about these problems?_**

**Comment by davidbritch** [comment]
Apologies for the delayed response - I've been on holiday.

The Xamarin.Forms Geocoder class just wraps the appropriate platform-specific geocoding class, thus giving you easy cross-platform support. So the Xamarin.Forms Geocoder class will enable you to use geocoding across multiple platforms, from shared code.

iOS:
1. I use Xamarin Studio where possible, and so recommend you ask in the forums on this issue.
2. Sounds like a locale issue (French formatting of strings, rather than English). I recommend you use this overload of Convert.ToDouble instead - https://msdn.microsoft.com/en-us/library/9s9ak971(v=vs.110).aspx

**Comment by nbsoftware** [comment]
Hello,
I have quite the same issue.
I downloaded the Xamarin Forms WorkingWithMaps sample, built it, signed it and added the appropriate Google API V2 KEY in the manifest.
On a genymotion emulator (API 19 and API 23), all is working correctly *BUT* the Geocode API (i.e. I'm seeing the map, I can add pins, I can reverse geocode but geocode always returns null).
Same issue alas on a real device (tested with the free version of https://app.testobject.com)
Everything (including geocoding) is working fine on iOS emulator.

**Comment by AlexTeixeira** [comment]
Same issue here for Geocode Api. 

**GetPositionsForAddressAsync** thrown _GRPC failed error_ & **GetAddressesForPositionAsync** return nothing.

**Comment by davidbritch** [comment]
I've just ran the Geocode and ReverseGeocode samples in the Google emulator and both worked fine, without any errors.

**Comment by AlexTeixeira** [comment]
@davidbritch  It's work for me in a device but not in the emulator

**Comment by davidbritch** [comment]
Does your emulator have Google Play Services installed and enabled?

**Comment by AlexTeixeira** [comment]
Yes I tried with Genymotion & AVD emulators. Both have Google Play Service working, Google Map working too. But now doesn't really matter for me but It can be usefull for people having the same issue.

**Comment by quicksilver65** [comment]
Sent from my T-Mobile 4G LTE Device


-------- Original message --------
