### ISSUE TITLE
Why do i get Web Page not  availabe error when i archieve it ?

### ISSUE THREAD

**Issue by ghost** [xamarin/recipes#33]
When i released my app and installed in my  android phone i got web page not found error  but when i built my solution in vs i get full output why?
![screenshot_2017-02-15-02-37-17](https://cloud.githubusercontent.com/assets/22939432/22949336/ee72fdf2-f327-11e6-8042-80e334154c2e.png)

**Comment by samirgc** [comment]
i got the solution from here


http://stackoverflow.com/questions/27740296/the-webview-running-in-the-emulator-in-android-studio-cannot-access-internet-bu
