### ISSUE TITLE
Unhandled Exception:  Java.IO.FileNotFoundException: <Timeout exceeded getting exception details> occurred

### ISSUE THREAD

**Issue by darksideofpotato** [xamarin/recipes#54]
Having some trouble implementing an audio recorder in my app, but seem to have the same problem with only the recipe code.

I get the follwing message at _recorder.Prepare();

Unhandled Exception:  Java.IO.FileNotFoundException: <Timeout exceeded getting exception details> occurred

I am testing on a Oneplus 5.

**Comment by lobrien** [comment]
It may be that the storage path on your device is different. Try to change line 32 of Activity1.cs to 

    string path = $"{Android.OS.Environment.ExternalStorageDirectory.AbsolutePath}/test.3gpp";

Also, the recipe does not explicitly set permissions, but that should cause an exception at the `SetAudioSource` line, which it looks like your code gets past. 

I am going to update the recipe shortly, but in the meantime, I assume that you've already added code similar to: 

    //Explicit permissions
    if (Build.VERSION.SdkInt > BuildVersionCodes.M)
    {
        if (CheckSelfPermission(Manifest.Permission.WriteExternalStorage) != Android.Content.PM.Permission.Granted
        || CheckSelfPermission(Manifest.Permission.RecordAudio) != Android.Content.PM.Permission.Granted)
        {
            RequestPermissions(new [] { Manifest.Permission.WriteExternalStorage, Manifest.Permission.RecordAudio}, 0);
        }
    }

**Comment by darksideofpotato** [comment]
Thank you for your help :) I did have to set permission for writing external storage after the code, but then I didn't get an error anymore. Now I just need to find out how to play back the recorded sound :)
