### ISSUE TITLE
does this record video support pause and resume record ?

### ISSUE THREAD

**Issue by wangjianpeng** [xamarin/recipes#67]
I know this record video project support start and stop record , how can i  pause and resume to record in this project ?

**Comment by bradumbaugh** [comment]
Hi @wangjianpeng, it doesn't look like this sample is set up for pausing and resuming. That said, you might look at the MediaRecorder's [pause](https://developer.xamarin.com/api/member/Android.Media.MediaPlayer.Pause()/) method. Take a look at [this Android doc](https://developer.android.com/reference/android/media/MediaPlayer) for a discussion about resuming.
