### ISSUE TITLE
How to display only one page of a pdf at a time?

### ISSUE THREAD

**Issue by vidhikhanna** [xamarin/recipes#68]
I want to display only one page at a time i.e. I do not want the scroll bar to load next page unless and until user clicks Next Page button (that is available on side menu).

Is their any configuration/setting available for that ? Or do I need to comment out certain code to achieve this behavior ?

**Comment by bradumbaugh** [comment]
Hi @vidhikhanna, this repository is for issues directly related to the recipes. For support with specific questions like this, take a look at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
