### ISSUE TITLE
The DisplayPDF iOS example does not work properly

### ISSUE THREAD

**Issue by julesx** [xamarin/recipes#8]
The iOS example cannot possibly be rendering correctly. This is what I see in my iPhone 4S simulator and on my iPhone 6S device.  No pages render full screen, they all tiled along the left side, and the last 4 pages never seem to load.

![2015-12-09 13 10 21](https://cloud.githubusercontent.com/assets/3010047/11694112/480c622a-9e76-11e5-9ba8-c07ee4cffd22.png)

**Comment by davidbritch** [comment]
Renders correctly when built in Xamarin Studio on a Mac. Investigating VS.

**Comment by julesx** [comment]
anything on this?
