### ISSUE TITLE
The DisplayPDF Droid example does not work properly on older APIs

### ISSUE THREAD

**Issue by julesx** [xamarin/recipes#9]
Here is a screenshot on my Android Emulator running API 17

![screenshot 2015-12-10 10 55 23](https://cloud.githubusercontent.com/assets/3010047/11720314/a9c0dd3c-9f2c-11e5-9142-1eeceddd4d5e.png)

However, it seems to work fine on my Moto X.

I'm guessing that this example only works on androids that use Chrome as the default browser?

This needs to be mentioned somewhere in the docs as this example is no good for people trying to support older versions and actually means we need another solution to deal with the older browser, especially since the example project targets API 15.

**Comment by davidbritch** [comment]
It's possible to get older APIs (I used API16) to display a pdf (using pdf.js) by hacking the JavaScript.

**Comment by julesx** [comment]
anything on this?

**Comment by davidbritch** [comment]
Set the Android project to a minimum API level of 19. Doc update will address earlier APIs.
